### ISSUE TITLE
Testing Needed

### ISSUE THREAD

**Issue by saprativa** [saprativa/wikipedia-summarizer#2]
@irakr please test the new version of the code with some random articles.

**Comment by irakr** [comment]
Ok.Im on it sir.

**Comment by irakr** [comment]
@saprativa Yes. It is working for various websites with their tables of similar structures. But some dont have tables and some have but with different patterns......search for: 'compiler' and 'programming language'. But ur is very good and I can barely understand....please explain me later.

**Comment by saprativa** [comment]
i will take care of the exceptions. u let me know if u find any more.

**Comment by saprativa** [comment]
@irakr i think the table on the wiki for compiler should not be included in the summary as it basically seems like a sort of table of contents. moreover the class attribute of the table is also different. what do u think?

![screenshot from 2016-02-17 19 45 29](https://cloud.githubusercontent.com/assets/16961851/13112026/206353f8-d5af-11e5-8c81-61b38a01f5cd.png)
![screenshot from 2016-02-17 19 49 36](https://cloud.githubusercontent.com/assets/16961851/13112142/a879b07a-d5af-11e5-9a15-b243e2e10eb5.png)

**Comment by irakr** [comment]
Yeah! I think it will b a gud idea 2 exclude tables for those pages where der is no table. I think the function print_infobox_table should only accept: class_='infobox'.....otherwise simply return. I guess!!!

**Comment by saprativa** [comment]
the infobox at https://en.wikipedia.org/wiki/SQL is not getting parsed correctly. need some modifications in the code.

**Comment by irakr** [comment]
I think for tables we can use the .children concept of beautifulsoup. I hv used this technique for those paras also. Its easier.

**Comment by saprativa** [comment]
ok..go ahead and modify as u like..but i think u shud first try to remove the citations
